// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fintech-terminal/Admin.tsx": () => import("../components/mockups/fintech-terminal/Admin.tsx"),
  "./components/mockups/fintech-terminal/Auth.tsx": () => import("../components/mockups/fintech-terminal/Auth.tsx"),
  "./components/mockups/fintech-terminal/Current.tsx": () => import("../components/mockups/fintech-terminal/Current.tsx"),
  "./components/mockups/fintech-terminal/Dashboard.tsx": () => import("../components/mockups/fintech-terminal/Dashboard.tsx"),
  "./components/mockups/fintech-terminal/Settings.tsx": () => import("../components/mockups/fintech-terminal/Settings.tsx")
};
